### ISSUE TITLE
Cross-compilation broken when building dlib

### ISSUE THREAD

**Issue by ghost** [deanproxy/eMail#1]
The host alias information is not passed to dlib's configure script. This needs to be done so that the resulting objects can be linked into email:

diff --git a/configure.in.dist b/configure.in.dist
index 91ad006..3d5c840 100644
--- a/configure.in.dist
+++ b/configure.in.dist
@@ -80,5 +80,5 @@ if test "$use_ssl" = "no"; then
        args="--without-ssl"
 fi
 cd dlib
-./configure $args
+./configure $args --host=$host_alias
 cd ..

**Comment by deanproxy** [comment]
Fixed.
