### ISSUE TITLE
ADDRESS_BOOK (2 issues)

### ISSUE THREAD

**Issue by towo-net** [deanproxy/eMail#18]
Freshly download, configure, make eMail (no package): email does not run out-of-the-box with the given sample file email.conf because it refers to ADDRESS_BOOK = '&/email.address.template' which does not exist.
I suggest to uncomment the config option in the sample file.

Also I suggest to not let it refer to '&' because address books are typically personal data.

(Furthermore, I didn't check this, but if there is a common address book format compatible with several mail clients, it would be appreciable if email supports it too.)

Proposal:
#ADDRESS_BOOK = '~/.addressbook'

**Comment by deanproxy** [comment]
If you do a make install, it will run as expected. The make install installs the address book in the default location.  If you don't want to do a make install then you can simply edit your configuration to reflect you special case or not use a configuration at all and just use command line arguments.

As for the default location, this is simply for examples and aren't meant to be specific for every user.. However,  there are a lot of users that use a global address book with the global configuration file as well as a lot of users that use a personal configuration file with a personal address book.  So changing this to suit another specific persons needs will not be expected and may make users that are upgrading have problems.
