### ISSUE TITLE
Do not overwrite the configuration file?

### ISSUE THREAD

**Issue by sindarina** [deanproxy/eMail#19]
I just discovered that two of our Windows hosts, hosts that had their Cygwin stuff updated recently, had their '/etc/email/email.conf' overwritten, apparently by the update that was applied. Nothing else touches it. Our own config could be restored from the backup, but ... it is something that should never, ever happen?

Could you take special care not to do this, please? Thanks!

**Comment by deanproxy** [comment]
The install.sh script is what does the copying over of the config file and it explicitly checks to make sure the config file doesn't already exist:

    if [ ! -f "$sysconf/email/email.conf" ]; then

So if there is already a config file present, it will not overwrite it.

I've also run a test to try to overwrite my config and I cannot reproduce that issue.

Can you reproduce the issue on your side and possibly do a little troubleshooting for me? Change your email.conf file and try to install again and see if it overwrites your file again?

Thanks!

**Comment by sindarina** [comment]
Reinstalling it via the Cygwin installer does not overwrite 'email.conf', but it does at the very least change the timestamp on the other files in the same directory, such as 'email.sig', to the time the installer was run. So I'm not sure how it happened, perhaps Cygwin behaves differently when it installs an update to a package?

**Comment by deanproxy** [comment]
I'm not responsible for the Cygwin package, so maybe you're correct. If the cygwin package is overwriting the files, I'd file a bug with the maintainer of that package.

**Comment by sindarina** [comment]
Ah, I see. I came here via the link in the signature, and I haven't been able to find anything in the files shipped with the package that suggests that the maintainer is someone else. I'll close this and poke around some more, see if I can find the actual package author.
