### ISSUE TITLE
email: FATAL: Smtp error: Timeout(10) while trying to read from SMTP server

### ISSUE THREAD

**Issue by PerfectClicks** [deanproxy/eMail#22]
Hi there,
I get this error sometimes. I think this is when my host is taking a little while to respond. 
I'm using $? to check the result, but it would be great it we could adjust the timeout setting?
Thanks,
Chad

**Comment by deanproxy** [comment]
You can either specify it in your email.conf with the TIMEOUT variable, or use the --timeout option.

**Comment by PerfectClicks** [comment]
Thanks for the response! 

Just to be clear, I enter the following into the conf file:
﻿TIMEOUT = '60' 
(This gives me an error).

Can you give me the proper format for specifying the TIMEOUT variable in the .conf file?

Thanks again :-)

**Comment by PerfectClicks** [comment]
Never mind, you've done a great job documenting in the man page. I'll use -x. Forgive me for not looking there first. I'm usually on top of small things like that. I just got caught up on the conf file. Thanks for making such a great script!

**Comment by deanproxy** [comment]
I may be mistaken about the TIMEOUT variable inside of the configuration file. I'll have to look again.  If it's not there, I can add that option.  However, yes, the --timeout or -x option should get you where you need to be currently.
