### ISSUE TITLE
email man page warnings

### ISSUE THREAD

**Issue by cjmayo** [deanproxy/eMail#3]
$ man email
Formatting page, please wait...
<standard input>:67: warning: macro `email.help'.' not defined (possibly missing space after `em')
<standard input>:95: warning: macro `URL' not defined (possibly missing space after `UR')
<standard input>:352: warning: macro `email'' not defined (possibly missing space after `em')

These do affect the content of the page too. Patch pasted below (don't think I can attach anything to this, hope it doesn't get mangled).

From 8c4ea00f653a21e2daef7e0bae4dea4c506355a5 Mon Sep 17 00:00:00 2001
From: Chris Mayo <aklhfex@gmail.com>
Date: Sun, 16 Oct 2011 12:14:31 +0100
Subject: [PATCH] Fix manual page warnings

---
 email.1.in |    7 ++++---
 1 files changed, 4 insertions(+), 3 deletions(-)

diff --git a/email.1.in b/email.1.in
index 0f46a8d..4669047 100644
--- a/email.1.in
+++ b/email.1.in
@@ -63,7 +63,7 @@ help section.
 
 The Help is not statically programmed into email.
 Instead it is a file in email's home directory called
-'email.help'.  It is updated regularly and will always
+\&'email.help'.  It is updated regularly and will always
 be rewritten with every release of email.
 
 .TP
@@ -91,7 +91,8 @@ subjects are allowed.
 .B \-\-encrypt | \-encrypt | \-e  
 This options allows you to encrypt your email message
 using 'gpg'. GPG can be obtained by going to:
-.URL http://www.gnupg.org.
+.UR http://www.gnupg.org
+.UE .
 When this option is specified, it will get the first
 recipient from the recipient list and it will encrypt
 the message using their key.  This key MUST be present
@@ -348,7 +349,7 @@ this variable is not set, it will default to vi.
 TMPDIR can be set to specify a temporary directory to
 place your temp files while email is working.  This is
 analogous to the TEMP_DIR variable in email.conf.  
-'email' will check TEMP_DIR first, then check your 
+\&'email' will check TEMP_DIR first, then check your 
 environment variable TMPDIR for a temporary directory.
 If neither contains a value, email defaults to /tmp.
 
-- 
1.7.6.1

**Comment by deanproxy** [comment]
Fixed.
