### ISSUE TITLE
./configure fails

### ISSUE THREAD

**Issue by KCaseySW** [deanproxy/eMail#32]
./configure terminates with
./configure: line 6700: ./configure: No such file or directory
on the following system:
Linux STOC-19x 4.4.0-28-generic #47~14.04.1-Ubuntu SMP Fri Jun 24 16:30:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
What am I missing?
Thanks
Kevin

**Comment by cjmayo** [comment]
Line 6699 in configure has ```cd dlib```
https://github.com/deanproxy/eMail/blob/master/configure#L6699

Is your dlib directory empty?

dlib's been split into a separate submodule:
https://github.com/deanproxy/dlib

**Comment by deanproxy** [comment]
I just now saw this...

As @cjmayo says, it's probably a missing dlib directory.  Make sure you run a recursive clone when you're pulling the latest from git:

    git clone --recursive https://github.com/deanproxy/eMail.git
