### ISSUE TITLE
error: no acceptable C compiler found in $PATH

### ISSUE THREAD

**Issue by echawkes** [deanproxy/eMail#39]
Hi, 

I've been trying to use the configure script to configure eMail for some time without success.  I can't get it to recognize any of the C compilers I have installed.  

I'm using Windows 10.  I have installed git-bash.  I also have Cygwin64 and Visual Studio 2015 Enterprise installed, 

I've installed gcc using cygwin64 (both the mingw version and regular gcc).  

I generally try adding the path to a specific compiler to the front of my PATH environment variable 

$ echo $PATH
/c/cygwin64/usr/x86_64-w64-mingw32/bin:/c/Users/echawkes/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/echawkes/bin:  ... (rest of path elided)

I always get a result like this in the git-bash shell, regardless of which compiler I try: 

$ ./configure
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/c/github.com/deanproxy/eMail.git/eMail':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
./configure: line 38: sort: No such file or directory
./configure: line 35: sed: No such file or directory

I haven't used git-bash before today - I installed it for the purpose of installing eMail - so I'm not very familiar with it. 

Any advice on how I can get set up to compile / configure eMail?

**Comment by echawkes** [comment]
A couple of other things I've tried that didn't work: 

Inside git-bash: 

$ echo $PATH
/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin:/c/Users/echawkes/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/echawkes/bin:     ... (rest of path elided)

$ ./configure
checking for gcc... no
checking for cc... no
checking for cl.exe... cl.exe
checking whether the C compiler works... no
configure: error: in `/c/github.com/deanproxy/eMail.git/eMail':
configure: error: C compiler cannot create executables
See `config.log' for more details


Inside cygwin:

$ pwd
/cygdrive/c/github.com/deanproxy/eMail.git/eMail
$ which perl
/usr/bin/perl
$ which gcc
/usr/bin/gcc
$ ./configure
./configure: line 16: $'\r': command not found
./configure: line 31: syntax error near unexpected token `newline'
'/configure: line 31: `     ;;

**Comment by deanproxy** [comment]
Are you trying to do this within cygwin?  In other words, did you open the cygwin terminal?  If so, when you type in `which gcc` what comes back?

**Comment by echawkes** [comment]
It's possible my last post went up while you were composing your post.  I think I was specific about which shell I was using in each case.  The git-bash shell says MINGW64 in the title bar.  

I'm more used to using Cygwin, but I'm willing to use git-bash if that's better supported.  

What combination of shell and compiler do you recommend?

**Comment by deanproxy** [comment]
I'm not sure how to help you, as I don't have a Windows machine around to test. I know that eMail has been compiled properly inside of CygWin, however.  As a matter of fact, I believe it is still a package that can be installed with the CygWin installer.

Try opening the CygWin shell and doing the compilation inside of there.

**Comment by echawkes** [comment]
I wasn't aware there was a cygwin package.  I installed it, and the program now runs under cygwin.  

Thanks for your help.

**Comment by deanproxy** [comment]
Woohoo! Glad that worked out.
