### ISSUE TITLE
Can this work with other MTAs like exim or postfix?

### ISSUE THREAD

**Issue by CMCDragonkai** [deanproxy/eMail#40]
Question in the title. Oh I just realised that you can symlink sendmail to exim, and these replacement MTAs attempt compatibility.

**Comment by deanproxy** [comment]
You can also specify the MTA you want to use in the email.conf file under SENDMAIL_BIN

**Comment by CMCDragonkai** [comment]
So I can specify a direct path to exim, instead of the standard sendmail binary. Cool.
