### ISSUE TITLE
./configure fails if the path to it contains spaces

### ISSUE THREAD

**Issue by mikhailnov** [deanproxy/eMail#42]
./configure fails if the path to it conatins spaces, e.g. if it '/home/user/Рабочий стол/eMail/configure'. You probably missed '' or "" somewhere.

**Comment by deanproxy** [comment]
Cannot reproduce.  You must run `configure` inside of the compiling directory where the`configure` script resides.  If the directory with the source and `configure` script is called eMail, then you must be inside that directory to run `./configure`.  I have tried putting the eMail directory inside multiple other directories, all with spaces in the name and cannot make it fail as reported.
