### ISSUE TITLE
 Unrecognized authentication type

### ISSUE THREAD

**Issue by etaylor75** [deanproxy/eMail#44]
I am trying to send email from email to an office365 mailbox but i keep getting 

email: FATAL: Smtp error: 504 5.7.4 Unrecognized authentication type [SN1NAM02FT025.eop-nam02.prod.protection.outlook.com]

i have changed ports and smtp-auth from login to plain, but still no go.

**Comment by deanproxy** [comment]
It's possible office365 using TLS encryption instead of just plain/login type authentication. Have you tried enabling TLS?  Can you paste you email.conf file and the command you're running?

**Comment by etaylor75** [comment]
# This is the DEFAULT configuration file for email.
#
# Please CHANGE THE VALUES below to suit your environment.
# Don't forget to set the shell environment variable EDITOR
############################################################

############################################################
# SMTP Server and Port number you use
############################################################
SMTP_SERVER = 'musacompanies-com.mail.protection.outlook.com'
SMTP_PORT = '25'

############################################################
# If you'd rather use sendmail binary, specify it and the
# command line switches to use, here.  If you have both
# this option and SMTP_SERVER set, SMTP_SERVER will be of
# higher priority than SENDMAIL.
############################################################
# SENDMAIL_BIN = '/usr/lib/sendmail -t -i'

############################################################
# Your email address: If you'd like To have your name to
# show in the from field instead of just your email address,
# then keep the format below and edit it to your email
# and name.
############################################################
#MY_NAME  = 'Your Real Name'
#MY_EMAIL = 'yourlogin@example.com'
#REPLY_TO = ''

############################################################
# If your mail server uses SSL or TLS in order to create
# a secure communication, set this to "true". Only very
# simple TLS is implemented at this time. In other words,
# there is no way to load your own certs just yet.
############################################################
USE_TLS = 'true'

############################################################
# Signature file and settings: Where is the signature file
# You can comment this out if you do not like signatures
############################################################
#SIGNATURE_FILE    = '&/email.sig'

############################################################
# This is where you store your address book... If you don't
# want address book functionality, just comment it out and
# use regular email addresses.
############################################################
#ADDRESS_BOOK = '&/email.address.template'

############################################################
# If you would like to have a copy Of your final email saved
# after it is sent, please specify a directory to save
# it in below... If not, just comment this field out and it
# won't save a sent file other wise, it will save it as
# email.sent in the directory below
############################################################
# SAVE_SENT_MAIL = '~'

############################################################
# With email, temporary files are stored with a random name
# Starting with .EM.  You must specify which directory you
# would like these temporary files stored while email is in
# Operation...  After email is done executing, it will remove
# Every temporary file it used.  The most common storage area
# for temporary files system wide is the /tmp directory
# if TEMP_DIR is not set, you can set the environment variable
# TMPDIR. If that is not set, email will just use /tmp
############################################################
# TEMP_DIR = '/tmp'

############################################################
# You should put the absolute path of your GPG binary
# In this variable.  If you do not know the absolute path
# just putting "gpg" will suffice if GPG is in your PATH
# environment variable path.
############################################################
# GPG_BIN = '/usr/bin/gpg'

###########################################################
# You can bypass email asking you for a password for gpg
# when you are encrypting or signing emails if you store
# it here.  Keep this safe! Make sure that people can't
# read your personal ~/.email.conf file if you're storing
# your password here!
###########################################################
# GPG_PASS =

###########################################################
# You can use SMTP_AUTH with email.  You just need to
# specify which type of SMTP AUTH you will use. Email
# support two types of SMTP AUTH: LOGIN and PLAIN.
# Typically, LOGIN is the most used amongst SMTP servers.
# If you are unsure, ask your ISP.
###########################################################
SMTP_AUTH = 'LOGIN'

###########################################################
# Setting your SMTP username is MANDITORY.  Please
# uncomment the option below and set your username in order
# to use SMTP AUTH
###########################################################
SMTP_AUTH_USER = ReportGenerator@musacompanies.com

###########################################################
# Setting your password is not manditory.  If you do not
# set your password, then email will prompt you for one
# if it sees that you are trying to use SMTP_AUTH.
###########################################################
SMTP_AUTH_PASS = ########

###########################################################
# If you have a v-card, you can have it attached to each
# message by specifying it's location here.
###########################################################
#VCARD = "~/dean.ldif"
#####
#VCARD = "~/dean.ldif"

Ernest Taylor
Director of Technology
Direct       904.899.8351
Email        etaylor@musacompanies.com<mailto:etaylor@musacompanies.com>

[cid:image001.png@01D36DB7.9F6FE6B0]

**Comment by deanproxy** [comment]
1. Make sure `SMTP_AUTH_USER` and `SMTP_AUTH_PASS` have single or double quotes around them.  I'm guessing they do in your actual config, but don't here.
2. Make sure the `SMTP_PORT` is set to 587 if you're using TLS.

**Comment by etaylor75** [comment]
When I change the port to 587 it times out:

email: FATAL: Could not connect to server: musacompanies-com.mail.protection.outlook.com on port: 587: Connection timed out

Ernest Taylor
Director of Technology
Direct       904.899.8351
Email        etaylor@musacompanies.com<mailto:etaylor@musacompanies.com>

[cid:image001.png@01D36DBA.5C1326E0]

**Comment by pszlazak** [comment]
Can you try with `outlook.office365.com`, TLS enabled and port set to 587?

**Comment by etaylor75** [comment]
I made the change and it look like the email was sent out but I never got it nor did the email ever hit my office365 mail system.

Ernest Taylor
Director of Technology
Direct       904.899.8351
Email        etaylor@musacompanies.com<mailto:etaylor@musacompanies.com>

[cid:image001.png@01D36DC3.5210F650]

**Comment by etaylor75** [comment]
It is working now thank you. The sending user email address was not correct.

Ernest Taylor
Director of Technology
Direct       904.899.8351
Email        etaylor@musacompanies.com<mailto:etaylor@musacompanies.com>

[cid:image001.png@01D36DC9.79C42C70]

**Comment by deanproxy** [comment]
@pszlazak thanks for the assist!
