### ISSUE TITLE
command not found after install

### ISSUE THREAD

**Issue by Zormgard** [deanproxy/eMail#46]
Hi there :) 

I have downloaded and configured the tool with succes. I then try with "make" but that results in "makefile:26: recipe fore target 'all' failed" - if i do a make install, that seems to work! - but when i want to use the email --help i get an bash: command not found..

i have also configured the email.conf file in /usr/local/etc/email - with my smtp2go credentials...

What do i have to do in order to get this working..?

 - Zormgard

**Comment by deanproxy** [comment]
Can you confirm that you followed these steps?

    git clone --recursive https://github.com/deanproxy/eMail.git
    cd eMail
    ./configure
    make
    make install

If you followed all of those steps completely (note the `--recursive` flag on the `git clone`), then your email binary should be in `/usr/local/bin/email`
