### ISSUE TITLE
Failure on configure

### ISSUE THREAD

**Issue by flybeaver163** [deanproxy/eMail#52]
Hi,

I downloaded the master code, and just run "./configure" and it fails as below:

......
_configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating email.help
config.status: creating email.1
config.status: creating include/config.h
**./configure: line 6740: ./configure: No such file or directory**

I checked the "configure" code, and its last three lines are:

cd dlib
./configure $args --host=$host_alias
cd ..

So it tried to run "configure" command in "dlib" folder and coudn't find the "configure" file.

It's the code issue, or I missed any step for running "configure"?
Thanks in advance for any hint.

**Comment by deanterm** [comment]
Did you clone the repo as described in the README? 

    git clone --recursive git@github.com:deanproxy/eMail.git

**Comment by flybeaver163** [comment]
I use the download function, instead of git command to pull the master repo.

**Comment by Stutemeyer** [comment]
Got the same error, even after cloning the repo.... so what can I do from here...?
ps. the "dlib" folder is empty.

Any hints are welcome.
thx

**Comment by deanterm** [comment]
`git clone --recursive https://github.com:deanproxy/eMail.git`

If the dlib folder is empty , you likely didn't use the `--recursive` flag

**Comment by Stutemeyer** [comment]
I did use the --recursive flag, but the dlib folder was still empty. 
Ended up downloading the missing files from https://github.com/davisking/dlib and unzipping/unpacking the them to the empty dlib folder.

**Comment by deanterm** [comment]
That won't work, as that's a completely different library. You're looking for https://github.com/deanproxy/dlib

**Comment by Stutemeyer** [comment]
Sorry..... You are absolutely right. Somehow I must have copied the wrong link. 
Everything seems to be installed correctly, just fiddling about with the conf-file and some SMTP-settings now :-)

**Comment by deanterm** [comment]
:+1: I'm uncertain why `--recursive` didn't work for you. I just gave it a shot and it cloned fine for me:

![image](https://user-images.githubusercontent.com/41060343/79154098-fe1e7300-7d9c-11ea-8966-153b7a43ae02.png)
