### ISSUE TITLE
SSL/TLS problems. 

### ISSUE THREAD

**Issue by Stutemeyer** [deanproxy/eMail#54]
Hi.

If I use port 25, I get this warning: "email: WARNING: No SSL support compiled in. Disabling TLS."
If I use port 465, I get this error: "email: FATAL: Smtp error: Timeout(10) while trying to read from SMTP server"
And if I use port 587, i get this error: "email: FATAL: Smtp error: 503 5.5.1 Error: authentication not enabled"

What can I do to avoid using port 25, and use port 465 or 587 instead?
and if that is not possible, what can I do to avoid the warning, when using port 25?

Hope someone can help with this problem

**Comment by deanproxy** [comment]
Make sure you have OpenSSL dev libraries installed.

**Comment by deanproxy** [comment]
Once you have the OpenSSL dev libraries installed, redo your `./configure`, `make`, `make install`

**Comment by Stutemeyer** [comment]
That solved my problem.
Thank you
