### ISSUE TITLE
error: You MUST specify the --version flag

### ISSUE THREAD

**Issue by rasa** [deanproxy/eMail#6]
Dean,

http://www.cleancode.org/projects/email states:

<pre>
git clone --recursive https://github.com/deanproxy/eMail.git
cd eMail
./configure
make
make install
</pre>

should work, but on Ubuntu 12.10, `make install` reports:

<pre>
./install.sh --bindir "/usr/local/bin" --sysconfdir "/usr/local/etc" \
                --mandir "/usr/local/share/man" --binext "" --version "" \
        --docdir "/usr/local/share/doc/"
error: You MUST specify the --version flag
make: *** [install] Error 2`
</pre>

If I install from http://www.cleancode.org/downloads/email/email-3.1.3.tar.gz , I do not have this issue.

Best,

Ross

**Comment by deanproxy** [comment]
Fixed Makefile to pull version from VERSION file.
